name: 'AKeyless Integrations'
description: 'Securely fetch and use static and dynamic secrets from AKeyless in your CI workflows.'
author: "Lance McCarthy and Connor Mancone"
branding:
  icon: 'unlock'
  color: 'green'
inputs:
  access-id:
    description: 'The access id of your auth method.'
    required: true
  access-type:
    description: 'Access type for login (JWT|AWS_IAM).'
    default: 'JWT'
    required: false
  api-url:
    description: 'The API endpoint to use, defaults to https://api.akeyless.io.'
    default: 'https://api.akeyless.io'
    required: false
  producer-for-aws-access:
    description: 'Path to an AWS dynamic producer. If provided, AWS credentials will be fetched from it and exported to the environment.'
    default: ''
    required: false
  static-secrets:
    description: 'A JSON object as a string, with a list of static secrets to fetch. The key should be the path to the secret and the value should be the name of the environment variable/output to save it to.'
    required: false
  dynamic-secrets:
    description: 'A JSON object as a string, with a list of dynamic secrets to fetch. The key should be the path to the secret and the value should be the name of the environment variable/output to save it to.'
    required: false
  export-secrets-to-outputs:
    description: 'True/False to denote if static/dynamic secrets should be exported as environment variables..'
    required: false
    default: true
  export-secrets-to-environment:
    description: 'True/False to denote if static/dynamic secrets should be exported as action outputs.'
    required: false
    default: true
  parse-dynamic-secrets:
    description: 'True/False to denote if dynamic secrets will exported as a single object, or parsed into individual outputs/env variables. Please visit the demos in ci.yml for clarification.'
    required: false
    default: false
runs:
  using: 'node16'
  main: 'src/index.js'
