name: 'Feature Dev Tests'

on:
  push:
    branches:
    - 'feature/*'

jobs:
  fetch_aws_dynamic_secrets:
    runs-on: ubuntu-latest
    name: Fetch AWS dynamic secrets
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Fetch dynamic secrets from AKeyless
      id: fetch-dynamic-secrets
      uses: ./
      with:
        access-id: ${{ secrets.AKEYLESS_ACCESS_ID }}
        dynamic-secrets: '{"/DevTools/test-grib":"AWS"}'
        separate-dynamic-secrets: true
        
    - name: Verify Outputs
      run: |
        echo "access_key_id: ${{ steps.fetch-dynamic-secrets.outputs.AWS_access_key_id }}"
        echo "id: ${{ steps.fetch-dynamic-secrets.outputs.AWS_id }}"
        echo "secret_access_key: ${{ steps.fetch-dynamic-secrets.outputs.AWS_secret_access_key }}"
        echo "security_token: ${{ steps.fetch-dynamic-secrets.outputs.AWS_security_token }}"
        echo "ttl_in_minutes: ${{ steps.fetch-dynamic-secrets.outputs.AWS_ttl_in_minutes }}"
        echo "type: ${{ steps.fetch-dynamic-secrets.outputs.AWS_type }}"
        echo "user: ${{ steps.fetch-dynamic-secrets.outputs.AWS_user }}"

    - name: Verify Vars
      run: |
        echo "access_key_id: ${{ env.AWS_access_key_id }}"
        echo "id: ${{ env.AWS_id }}"
        echo "secret_access_key: ${{ env.AWS_secret_access_key }}"
        echo "security_token: ${{ env.AWS_security_token }}"
        echo "ttl_in_minutes: ${{ env.AWS_ttl_in_minutes }}"
        echo "type: ${{ env.AWS_type }}"
        echo "user: ${{ env.AWS_user }}"

  fetch_sql_dynamic_secrets:
    runs-on: ubuntu-latest
    name: Fetch SQL dynamic secrets
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Fetch dynamic secrets from AKeyless
      id: fetch-dynamic-secrets
      uses: ./
      with:
        access-id: ${{ secrets.AKEYLESS_ACCESS_ID }}
        dynamic-secrets: '{"/DevTools/az-sqlsrvsecret":"SQL"}'
        separate-dynamic-secrets: true
        
    - name: Verify Vars
      run: |
        echo "ID: ${{ env.SQL_id }}"
        echo "USER: ${{ env.SQL_user }}"
        echo "TTL_IN_MINUTES: ${{ env.SQL_ttl_in_minutes }}"
        echo "PASSWORD: ${{ env.SQL_password }}"

    - name: Verify Outputs
      run: |
        echo "ID: ${{ steps.fetch-dynamic-secrets.outputs.SQL_id }}" 
        echo "USER: ${{ steps.fetch-dynamic-secrets.outputs.SQL_user }}" 
        echo "TTL_IN_MINUTES: ${{ steps.fetch-dynamic-secrets.outputs.SQL_ttl_in_minutes }}" 
        echo "PASSWORD: ${{ steps.fetch-dynamic-secrets.outputs.SQL_password }}"

