name: 'CI New Feature Tests'

on:
  push:
    branches:
    - 'feature/*'

jobs:

##########################################################
########## SIMPLE JOB FOR WORKFLOW VALIDATION ############
##########################################################
  static_secrets:
    runs-on: ubuntu-latest
    name: Fetch static secrets
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Fetch static secrets from AKeyless
      id: fetch-secrets
      uses: ./
      with:
        access-id: ${{ secrets.AKEYLESS_ACCESS_ID }}
        static-secrets: '{"/DevTools/my-static-secret":"my_static_secret"}'

    - name: Verify Job Outputs
      run: echo "Your output secret is ${{ steps.fetch-secrets.outputs.my_static_secret }}"

    - name: Verify Environment Variables
      run: echo "Your environment secret is ${{ env.my_static_secret }}"

##########################################################
########## NEW FEATURE TESTS BELOW THIS LINE #############
##########################################################

  github_dynamic_secrets:
    runs-on: ubuntu-latest
    name: GitHub dynamic secrets (default)
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Fetch GitHub dynamic secrets from Akleyless
      id: fetch-secrets
      uses: ./
      with:
        access-id: ${{ secrets.AKEYLESS_ACCESS_ID }}
        dynamic-secrets: '{"/DevTools/github-secret":"github_dynamic_secret"}'

    - name: Verify Job Outputs
      run: |
        echo "Your job output secret is ${{ steps.fetch-secrets.outputs.github_dynamic_secret }}"

    - name: Verify Environment Variables
      run: |
        echo "Your environment secret is ${{ env.github_dynamic_secret }}"
