name: 'CI Tests'

on:
  push:
    branches:
    - 'investigation/*'

jobs:
  fetch_static_secrets:
    runs-on: ubuntu-latest
    name: Fetch static secrets
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Fetch static secrets from AKeyless
      id: fetch-static-secrets
      uses: ./
      with:
        access-id: ${{ secrets.AKEYLESS_ACCESS_ID }}
        static-secrets: '{"/DevTools/my-static-secret":"my_static_secret"}'

    - name: Verify static secrets output
      run: |
        echo "[static] Your output secret is ${{ steps.fetch-static-secrets.my_static_secret }}"
        echo "[static] Your environment secret is ${{ env.my_static_secret }}"

  fetch_aws_dynamic_secrets:
    runs-on: ubuntu-latest
    name: Fetch AWS dynamic secrets (default)
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Fetch dynamic secrets from AKeyless
      id: fetch-aws-secrets
      uses: LanceMcCarthy/akeyless-action@v3.0.0
      with:
        access-id: ${{ secrets.AKEYLESS_ACCESS_ID }} # Looks like p-fq3afjjxv839
        dynamic-secrets: '{"/DevTools/test-grib":"aws_dynamic_secrets"}'
        
    - name: EXTRA 1 - Export Secrets to Environment using jq
      run: |
        echo '${{ steps.fetch-aws-secrets.outputs.aws_dynamic_secrets }}' | jq -r 'to_entries|map("AKEYLESS_\(.key)=\(.value|tostring)")|.[]' >> $GITHUB_ENV

    - name: EXTRA 2 - Verify Exports
      run: |
        echo "access_key_id: ${{ env.AKEYLESS_access_key_id }}"
        echo "id: ${{ env.AKEYLESS_id }}"
        echo "secret_access_key: ${{ env.AKEYLESS_secret_access_key }}"
        echo "security_token: ${{ env.AKEYLESS_security_token }}"
        echo "ttl_in_minutes: ${{ env.AKEYLESS_ttl_in_minutes }}"
        echo "type: ${{ env.AKEYLESS_type }}"
        echo "user: ${{ env.AKEYLESS_user }}"

    - name: Fetch AWS dynamic secrets (parsed)
      id: aws-secrets-parsed
      uses: LanceMcCarthy/akeyless-action@v3.0.0
      with:
        access-id: ${{ secrets.AKEYLESS_ACCESS_ID }}
        dynamic-secrets: '{"/DevTools/test-grib":""}'
        parse-dynamic-secrets: true

    - name: Verify Parsed Outputs
      run: |
        echo "access_key_id: ${{ steps.aws-secrets-parsed.outputs.access_key_id }}"
        echo "id: ${{ steps.aws-secrets-parsed.outputs.id }}"
        echo "secret_access_key: ${{ steps.aws-secrets-parsed.outputs.secret_access_key }}"
        echo "security_token: ${{ steps.aws-secrets-parsed.outputs.security_token }}"
        echo "ttl_in_minutes: ${{ steps.aws-secrets-parsed.outputs.ttl_in_minutes }}"
        echo "type: ${{ steps.aws-secrets-parsed.outputs.type }}"
        echo "user: ${{ steps.aws-secrets-parsed.outputs.user }}"

    - name: Verify Parsed Vars
      run: |
        echo "access_key_id: ${{ env.access_key_id }}"
        echo "id: ${{ env.id }}"
        echo "secret_access_key: ${{ env.secret_access_key }}"
        echo "security_token: ${{ env.security_token }}"
        echo "ttl_in_minutes: ${{ env.ttl_in_minutes }}"
        echo "type: ${{ env.type }}"
        echo "user: ${{ env.user }}"

    - name: Fetch AWS dynamic secrets (prefixed)
      id: aws-secrets-prefixed
      uses: LanceMcCarthy/akeyless-action@v3.0.0
      with:
        access-id: ${{ secrets.AKEYLESS_ACCESS_ID }}
        dynamic-secrets: '{"/DevTools/test-grib":"AWS"}'
        parse-dynamic-secrets: true

    - name: Verify Job Outputs
      run: |
        echo "access_key_id: ${{ steps.aws-secrets-prefixed.outputs.AWS_access_key_id }}"
        echo "id: ${{ steps.aws-secrets-prefixed.outputs-prefixed.AWS_id }}"
        echo "secret_access_key: ${{ steps.aws-secrets-prefixed.outputs.AWS_secret_access_key }}"
        echo "security_token: ${{ steps.aws-secrets-prefixed.outputs.AWS_security_token }}"
        echo "ttl_in_minutes: ${{ steps.aws-secrets-prefixed.outputs.AWS_ttl_in_minutes }}"
        echo "type: ${{ steps.aws-secrets-prefixed.outputs.AWS_type }}"
        echo "user: ${{ steps.aws-secrets-prefixed.outputs.AWS_user }}"

    - name: Verify Environment Variables
      run: |
        echo "access_key_id: ${{ env.AWS_access_key_id }}"
        echo "id: ${{ env.AWS_id }}"
        echo "secret_access_key: ${{ env.AWS_secret_access_key }}"
        echo "security_token: ${{ env.AWS_security_token }}"
        echo "ttl_in_minutes: ${{ env.AWS_ttl_in_minutes }}"
        echo "type: ${{ env.AWS_type }}"
        echo "user: ${{ env.AWS_user }}"

  fetch_sql_dynamic_secrets:
    runs-on: ubuntu-latest
    name: Fetch SQL dynamic secrets
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Fetch SQL dynamic secrets (default)
      id: fetch-dynamic-secrets
      uses: LanceMcCarthy/akeyless-action@v3.0.0
      with:
        access-id: ${{ secrets.AKEYLESS_ACCESS_ID }}
        dynamic-secrets: '{"/DevTools/az-sqlsrvsecret":"my_dynamic_secret"}'

    - name: Verify Fetch Job Environment Variables
      run: |
        # echo "[Env Var] Your environment secret is ${{ env.my_dynamic_secret }}"
        echo "ID:"
        echo '${{ env.my_dynamic_secret }}' | jq '.id'
        echo "USER:"
        echo '${{ env.my_dynamic_secret }}' | jq '.user'
        echo "TTL_IN_MINUTES:"
        echo '${{ env.my_dynamic_secret }}' | jq '.ttl_in_minutes'
        echo "PASSWORD:"
        echo '${{ env.my_dynamic_secret }}' | jq '.password'

    - name: Verify Fetch Job Outputs
      run: |
        #echo "[Job Output] Your output secret is ${{ steps.fetch-dynamic-secrets.outputs.my_dynamic_secret }}"
        echo "ID:" 
        echo '${{ steps.fetch-dynamic-secrets.outputs.my_dynamic_secret }}' | jq '.id'
        echo "USER:" 
        echo '${{ steps.fetch-dynamic-secrets.outputs.my_dynamic_secret }}' | jq '.user'
        echo "TTL_IN_MINUTES:" 
        echo '${{ steps.fetch-dynamic-secrets.outputs.my_dynamic_secret }}' | jq '.ttl_in_minutes'
        echo "PASSWORD:"
        echo '${{ steps.fetch-dynamic-secrets.outputs.my_dynamic_secret }}' | jq '.password'

    - name: EXTRA 1 - Export Secrets to Environment using jq
      run: |
        echo '${{ steps.fetch-dynamic-secrets.outputs.my_dynamic_secret }}' | jq -r 'to_entries|map("AKEYLESS_\(.key)=\(.value|tostring)")|.[]' >> $GITHUB_ENV
    
    - name: EXTRA 2 - Verify Export Variables
      run: |
        echo "AKEYLESS_id = ${{ env.AKEYLESS_id }}"
        echo "AKEYLESS_user = ${{ env.AKEYLESS_user }}"
        echo "AKEYLESS_password = ${{ env.AKEYLESS_password }}"
        echo "AKEYLESS_ttl_in_minutes = ${{ env.AKEYLESS_ttl_in_minutes }}"

    - name: Fetch SQL dynamic secrets (parsed)
      id: sql-secrets-parsed
      uses: LanceMcCarthy/akeyless-action@v3.0.0
      with:
        access-id: ${{ secrets.AKEYLESS_ACCESS_ID }}
        dynamic-secrets: '{"/DevTools/test-grib":""}'
        parse-dynamic-secrets: true

    - name: Verify Parsed Outputs
      run: |
        echo "access_key_id: ${{ steps.sql-secrets-parsed.outputs.access_key_id }}"
        echo "id: ${{ steps.sql-secrets-parsed.outputs.id }}"
        echo "secret_access_key: ${{ steps.sql-secrets-parsed.outputs.secret_access_key }}"
        echo "security_token: ${{ steps.sql-secrets-parsed.outputs.security_token }}"
        echo "ttl_in_minutes: ${{ steps.sql-secrets-parsed.outputs.ttl_in_minutes }}"
        echo "type: ${{ steps.sql-secrets-parsed.outputs.type }}"
        echo "user: ${{ steps.sql-secrets-parsed.outputs.user }}"

    - name: Verify Parsed Vars
      run: |
        echo "access_key_id: ${{ env.access_key_id }}"
        echo "id: ${{ env.id }}"
        echo "secret_access_key: ${{ env.secret_access_key }}"
        echo "security_token: ${{ env.security_token }}"
        echo "ttl_in_minutes: ${{ env.ttl_in_minutes }}"
        echo "type: ${{ env.type }}"
        echo "user: ${{ env.user }}"

    - name: Fetch SQL dynamic secrets (prefixed)
      id: sql-secrets-prefix
      uses: LanceMcCarthy/akeyless-action@v3.0.0
      with:
        access-id: ${{ secrets.AKEYLESS_ACCESS_ID }}
        dynamic-secrets: '{"/DevTools/az-sqlsrvsecret":"SQL"}'
        parse-dynamic-secrets: true

    - name: Verify Outputs
      run: |
        echo "ID: ${{ steps.sql-secrets-prefix.outputs.SQL_id }}" 
        echo "USER: ${{ steps.sql-secrets-prefix.outputs.SQL_user }}" 
        echo "TTL_IN_MINUTES: ${{ steps.sql-secrets-prefix.outputs.SQL_ttl_in_minutes }}" 
        echo "PASSWORD: ${{ steps.sql-secrets-prefix.outputs.SQL_password }}"

    - name: Verify Vars
      run: |
        echo "ID: ${{ env.SQL_id }}"
        echo "USER: ${{ env.SQL_user }}"
        echo "TTL_IN_MINUTES: ${{ env.SQL_ttl_in_minutes }}"
        echo "PASSWORD: ${{ env.SQL_password }}"