name: 'CI Tests'

on:
  push:
    branches: [ 'investigation/*' ]

jobs:
  fetch_static_secrets:
    runs-on: ubuntu-latest
    name: Fetch some static secrets
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Fetch static secrets from AKeyless
      id: fetch-static-secrets
      uses: ./
      with:
        access-id: 'p-fq3qbjjxv839'
        static-secrets: '{"/personal-keys/mccarthy/MyFirstSecret":"my_first_secret"}'
        export-secrets-to-outputs: true
        export-secrets-to-environment: true
        
    - name: Verify static secrets output
      run: |
        echo "[static] Your output secret is ${{ steps.fetch-static-secrets.outputs.my_first_secret }}"
        echo "[static] Your environment secret is ${{ env.my_first_secret }}"
        
    - name: Fetch dynamic secrets from AKeyless
      id: fetch-dynamic-secrets
      uses: ./
      with:
        access-id: 'p-fq3qbjjxv839'
        dynamic-secrets: '{"/DevTools/dvlup-azure":"my_dynamic_secret"}'
        export-secrets-to-outputs: true
        export-secrets-to-environment: true
        
    - name: Verify dynamic secrets output
      run: |
        echo "[dynamic] Your output secret is ${{ steps.fetch-dynamic-secrets.my_dynamic_secret }}"
        echo "[dynamic] Your environment secret is ${{ env.my_dynamic_secret }}"
        
