name: 'CI Tests'

on:
  push:
    branches: [ 'investigation/*' ]

jobs:
  fetch_static_secrets:
    runs-on: ubuntu-latest
    name: Fetch static secrets
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Fetch static secrets from AKeyless
      id: fetch-static-secrets
      uses: ./
      with:
        access-id: ${{ secrets.AKEYLESS_ACCESS_ID }}
        static-secrets: '{"/DevTools/my-static-secret":"my_static_secret"}'
        export-secrets-to-outputs: true
        export-secrets-to-environment: true
        
    - name: Verify static secrets output
      run: |
        echo "[static] Your output secret is ${{ steps.fetch-static-secrets.my_static_secret }}"
        echo "[static] Your environment secret is ${{ env.my_static_secret }}"

  fetch_dynamic_secrets:
    runs-on: ubuntu-latest
    name: Fetch dynamic secrets
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Fetch dynamic secrets from AKeyless
      id: fetch-dynamic-secrets
      uses: ./
      with:
        access-id: ${{ secrets.AKEYLESS_ACCESS_ID }}
        dynamic-secrets: '{"/DevTools/az-sqlsrvsecret":"my_dynamic_secret"}'
        export-secrets-to-outputs: true
        export-secrets-to-environment: true
        
    - name: Verify Fetch Job Environment Variables
      run: |
        echo "[Env Var] Your environment secret is ${{ env.my_dynamic_secret }}"
        echo '${{ env.my_dynamic_secret }}' | jq '.id'
        echo '${{ env.my_dynamic_secret }}' | jq '.ttl_in_minutes'
        echo '${{ env.my_dynamic_secret }}' | jq '.user'
        echo '${{ env.my_dynamic_secret }}' | jq '.password'


    - name: Verify Fetch Job Outputs
      run: |
        echo "[Job Output] Your output secret is ${{ steps.fetch-dynamic-secrets.outputs.my_dynamic_secret }}"
        # jq should already be installed on the runner
        echo '${{ steps.fetch-dynamic-secrets.outputs.my_dynamic_secret }}' | jq -r 'to_entries|map("AKEYLESS_\(.key) = \(.value|tostring)")|.[]'
        echo '${{ steps.fetch-dynamic-secrets.outputs.my_dynamic_secret }}' | jq -r 'to_entries|map("AKEYLESS_\(.key) = \(.value|tostring)")|.[]' >> $GITHUB_ENV

    -name: Confirm GitHub runner Env Vars
      run: |
        echo "AKEYLESS_id = ${{ env.AKEYLESS_id }}"
        echo "AKEYLESS_user = ${{ env.AKEYLESS_user }}"
        echo "AKEYLESS_password = ${{ env.AKEYLESS_password }}"
        echo "AKEYLESS_ttl_in_minutes = ${{ env.AKEYLESS_ttl_in_minutes }}"
