name: 'CI Tests'

on:
  push:
    branches: [ 'investigation/*' ]

jobs:
  fetch_static_secrets:
    runs-on: ubuntu-latest
    name: Fetch static secrets
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Fetch static secrets from AKeyless
      id: fetch-static-secrets
      uses: ./
      with:
        access-id: ${{ secrets.AKEYLESS_ACCESS_ID }}
        static-secrets: '{"/DevTools/my-static-secret":"my_static_secret"}'
        export-secrets-to-outputs: true
        export-secrets-to-environment: true
        
    - name: Verify static secrets output
      run: |
        echo "[static] Your output secret is ${{ steps.fetch-static-secrets.my_static_secret }}"
        echo "[static] Your environment secret is ${{ env.my_static_secret }}"

  fetch_aws_dynamic_secrets:
    runs-on: ubuntu-latest
    name: Fetch AWS dynamic secrets
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Fetch dynamic secrets from AKeyless
      id: fetch-dynamic-secrets
      uses: ./
      with:
        access-id: ${{ secrets.AKEYLESS_ACCESS_ID }} # Looks like p-fq3afjjxv839
        dynamic-secrets: '{"/DevTools/test-grib":"aws_dynamic_secrets"}'
        
    - name: Export Secrets to Environment
      run: |
        echo '${{ steps.fetch-dynamic-secrets.outputs.aws_dynamic_secrets }}' | jq -r 'to_entries|map("AWS_\(.key)=\(.value|tostring)")|.[]' >> $GITHUB_ENV

    - name: Verify Vars
      run: |
        echo "access_key_id: ${{ env.AWS_access_key_id }}"
        echo "id: ${{ env.AWS_id }}"
        echo "secret_access_key: ${{ env.AWS_secret_access_key }}"
        echo "security_token: ${{ env.AWS_security_token }}"
        echo "ttl_in_minutes: ${{ env.AWS_ttl_in_minutes }}"
        echo "type: ${{ env.AWS_type }}"
        echo "user: ${{ env.AWS_user }}"

  fetch_sql_dynamic_secrets:
    runs-on: ubuntu-latest
    name: Fetch SQL dynamic secrets
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Fetch dynamic secrets from AKeyless
      id: fetch-dynamic-secrets
      uses: ./
      with:
        access-id: ${{ secrets.AKEYLESS_ACCESS_ID }}
        dynamic-secrets: '{"/DevTools/az-sqlsrvsecret":"my_dynamic_secret"}'
        export-secrets-to-outputs: true
        export-secrets-to-environment: true
        
    - name: Verify Fetch Job Environment Variables
      run: |
        # echo "[Env Var] Your environment secret is ${{ env.my_dynamic_secret }}"
        echo "ID:"
        echo '${{ env.my_dynamic_secret }}' | jq '.id'
        echo "USER:"
        echo '${{ env.my_dynamic_secret }}' | jq '.user'
        echo "TTL_IN_MINUTES:"
        echo '${{ env.my_dynamic_secret }}' | jq '.ttl_in_minutes'
        echo "PASSWORD:"
        echo '${{ env.my_dynamic_secret }}' | jq '.password'

    - name: Verify Fetch Job Outputs
      run: |
        #echo "[Job Output] Your output secret is ${{ steps.fetch-dynamic-secrets.outputs.my_dynamic_secret }}"
        echo "ID:" 
        echo '${{ steps.fetch-dynamic-secrets.outputs.my_dynamic_secret }}' | jq '.id'
        echo "USER:" 
        echo '${{ steps.fetch-dynamic-secrets.outputs.my_dynamic_secret }}' | jq '.user'
        echo "TTL_IN_MINUTES:" 
        echo '${{ steps.fetch-dynamic-secrets.outputs.my_dynamic_secret }}' | jq '.ttl_in_minutes'
        echo "PASSWORD:"
        echo '${{ steps.fetch-dynamic-secrets.outputs.my_dynamic_secret }}' | jq '.password'

    - name: EXTRA A - Export Job Outputs to Separate GitHub Runner Env Vars
      run: echo '${{ steps.fetch-dynamic-secrets.outputs.my_dynamic_secret }}' | jq -r 'to_entries|map("AKEYLESS_\(.key)=\(.value|tostring)")|.[]' >> $GITHUB_ENV
    
    - name: EXTRA B - Confirm GitHub Runner Env Vars
      run: |
        echo "AKEYLESS_id = ${{ env.AKEYLESS_id }}"
        echo "AKEYLESS_user = ${{ env.AKEYLESS_user }}"
        echo "AKEYLESS_password = ${{ env.AKEYLESS_password }}"
        echo "AKEYLESS_ttl_in_minutes = ${{ env.AKEYLESS_ttl_in_minutes }}"
