name: 'CI'

on:
  push:
    branches: [ 'main' ]

jobs:
  fetch_static_secrets:
    runs-on: ubuntu-latest
    name: Fetch static secrets
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Fetch static secrets from AKeyless
      id: fetch-static-secrets
      uses: ./
      with:
        access-id: ${{ secrets.AKEYLESS_ACCESS_ID }} # Looks like p-fq3afjjxv839
        static-secrets: '{"/DevTools/my-static-secret":"my_static_secret"}' # confirm correct path AND your JWT token is allowed to use this secret
        export-secrets-to-outputs: true
        export-secrets-to-environment: true
        
    - name: Output static secrets (masked in output)
      run: |
        echo "[static] Your output secret is ${{ steps.fetch-static-secrets.outputs.my_first_secret }}"
        echo "[static] Your environment secret is ${{ env.my_first_secret }}"

  fetch_dynamic_secrets:
    runs-on: ubuntu-latest
    name: Fetch dynamic secrets
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Fetch dynamic secrets from AKeyless
      id: fetch-dynamic-secrets
      uses: ./
      with:
        access-id: ${{ secrets.AKEYLESS_ACCESS_ID }} # Looks like p-fq3afjjxv839
        dynamic-secrets: '{"/DevTools/az-sqlsrvsecret":"dynamic_sqlsrv_secret"}'
        
    - name: Verify Environment Variables output
      run: |
        echo "[Env Var] Your environment secret is ${{ env.dynamic_sqlsrv_secret }}"

    - name: Verify Job Outputs
      run: |
        echo "[Job Output] Your output secret is ${{ steps.fetch-dynamic-secrets.outputs.dynamic_sqlsrv_secret }}"