name: 'CI'

on:
  push:
    branches:
      - main
  pull_request:
    branches:    
      - main

jobs:
  fetch_static_secrets:
    runs-on: ubuntu-latest
    name: Fetch some static secrets
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Fetch static secrets from AKeyless
      id: fetch-static-secrets
      uses: ./   # IMPORTANT - in your workflow, this should be 'uses: LanceMcCarthy/akeyless-action@v2'
      with:
        access-id: ${{ secrets.AKEYLESS_ACCESS_ID }}
        static-secrets: '{"/personal-keys/mccarthy/MyFirstSecret":"my_first_secret"}'
        export-secrets-to-outputs: true
        export-secrets-to-environment: true
        
    - name: Output your secret (this should be masked in logs and terminal output)
      run: |
        echo "Your output secret is ${{ steps.fetch-static-secrets.outputs.my_first_secret }}"
        echo "Your environment secret is ${{ env.my_first_secret }}"