name: 'Azure AD Dynamic Secrets NEW'
# Docs => https://docs.akeyless.io/docs/azure-ad-dynamic-secrets

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'src/**/*'
      - 'package.json'
      - 'package-lock.json'
      - '.github/workflows/dynamic-azure-ad-new.yml'

jobs:
  ##############################
  ########## Option 1 ########## 
  ##############################
  # - Uses default behavior 
  # The response from Akeyless is kept in it's original JSON string. It is then your responsibility to correctly parse it.
  
  fetch_dynamic_secrets:
    runs-on: ubuntu-latest
    name: AAD dynamic secrets (default)
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Fetch dynamic secret from Akleyless
      id: fetch-secrets
      uses: akeyless-community/akeyless-github-action@v1.0.0
      with:
        access-id: ${{ secrets.AKEYLESS_ACCESS_ID }}
        dynamic-secrets: |
          - name: "/DevTools/live-azure-ad"
            output-name: "azure_ad_dynamic_secret"
        access-type: jwt

    - name: Verify Job Outputs
      run: |
        echo "ID: ${{ steps.fetch-secrets.outputs.id }}" 
        echo "MSG: ${{ steps.fetch-secrets.outputs.msg }}"
        echo "SECRET: ${{ steps.fetch-secrets.outputs.secret }}"
        echo "TTL_IN_MINUTES: ${{ steps.fetch-secrets.outputs.ttl_in_minutes }}"
  
    - name: Verify Environment Variables
      run: |
        echo "ID: ${{ env.id }}"
        echo "MSG: ${{ env.msg }}"
        echo "SECRET: ${{ env.secret }}"
        echo "TTL_IN_MINUTES: ${{ env.ttl_in_minutes }}"
