name: 'Static Secrets'
# Docs => https://docs.akeyless.io/docs/create-secret

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'src/**/*'
      - 'package.json'
      - 'package-lock.json'
      - '.github/workflows/static-secrets.yml'

permissions:
  id-token: write
  contents: read

jobs:
  static_secret:
    runs-on: ubuntu-latest
    name: Fetch static secrets
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Fetch static secret from AKeyless
      id: fetch-secrets
      uses: ./
      with:
        access-id: ${{ secrets.AKEYLESS_ACCESS_ID }}
        static-secrets: '{"/DevTools/my-static-secret":"my_static_secret"}'

    - name: Verify Job Outputs
      run: echo "Your output secret is ${{ steps.fetch-secrets.outputs.my_static_secret }}"

    - name: Verify Environment Variables
      run: echo "Your environment secret is ${{ env.my_static_secret }}"

# ----------------- personal akeyless account ----------------- #

  static_secret_p:
    runs-on: ubuntu-latest
    name: Fetch static [p]
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Fetch static secret from AKeyless
      id: fetch-secrets
      uses: ./
      with:
        access-id: ${{secrets.AKEYLESS_ACCESS_ID_PERSONAL}}
        static-secrets: '{"/my-first-secret":"my_static_secret"}'

    - name: Verify Job Outputs
      run: echo "Your output secret is ${{steps.fetch-secrets.outputs.my_static_secret}}"

    - name: Verify Environment Variables
      run: echo "Your environment secret is ${{env.my_static_secret}}"